### PR TITLE
Use slash instead of path.sep for regular expressions. Fix tests for Windows. Re-fix #13

### LINKED ISSUE #13: Importing `imports/server/XXX.js` from `server/main.js` causes an ESLint error on Windows
I assume that Windows-specific directory delimiter `\` causes this problem.
I created a reproduction repository. I got the following errors.
https://github.com/exKAZUu/test-eslint-import-resolver-meteor

```
C:\Users\exKAZUu\Desktop\test-eslint-import-resolver-meteor>npm run eslint

> test-eslint-import-resolver-meteor@ eslint C:\Users\exKAZUu\Desktop\test-eslint-import-resolver-meteor
> eslint . --fix

The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.

C:\Users\exKAZUu\Desktop\test-eslint-import-resolver-meteor\server\main.js
  3:32  error  Unable to resolve path to module '../imports/server/value34'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by exKAZUu**
- Revert #14 because my old fix was wrong.
- `clientRe` and `serverRe` expect that a path string includes `/` so my new fix replaces `path.sep` with `/`.
- Test cases use `/` and cause test failures on Windows so I replace `/` with `path.sep`.

### CODE REVIEW

**Comment by exKAZUu** [comment]
I confirmed there is no test failure on Windows.

```
  paths
    √ handles base path relative to CWD
    √ handles root (/) paths relative to CWD
    √ should not resolve a client file in a server file
    √ should not resolve a client file in a non-client file
    √ should not resolve a file ending in client in a non-client file
    √ should not resolve a server file in a client file
    √ should not resolve a server file in a non-server file
    √ should not resolve a file ending in server in a non-server file
    √ should resolve a file ending in server in a non-server file if it comes from a node module
    √ should resolve a custom Meteor package if it is in the packages file
    √ should not resolve a custom Meteor package if it is not in the packages file
    √ should resolve a built-in Meteor package if it is in the versions file
    √ should not resolve a built-in Meteor package if it is not in the versions file


  13 passing (23ms)
```

File: test/paths.js [hunk 1]
```diff
@@ -5,75 +5,75 @@ var meteorResolver = require('../index.js')
...
 
   it('should not resolve a client file in a server file', function () {
-    expect(meteorResolver.resolve('/imports/client/client-test', './test/imports/server/server-test.js'))
+    expect(meteorResolver.resolve('/imports/client/client-test', './test/imports/server/server-test.js'.replace(/\//g, path.sep)))
       .to.deep.equal({found: false})
   })
 
   it('should not resolve a client file in a non-client file', function () {
-    expect(meteorResolver.resolve('/imports/client/client-test', './test/imports/package-test/plain-file.js'))
+    expect(meteorResolver.resolve('/imports/client/client-test', './test/imports/package-test/plain-file.js'.replace(/\//g, path.sep)))
```
Comment (clayne11) [inline test/paths.js]: Can you turn this into a function? You copied the same code on every single test. Makes sense to abstract it.

File: index.js [hunk 2]
```diff
@@ -23,7 +23,8 @@ exports.resolve = function (source, file, config) {
     meteorSource = path.resolve(meteorRoot, source.substr(1))
   }
 
-  if (!isNodeModuleImport(source) && (isClientInNonClient(source, file) || isServerInNonServer(source, file))) {
+  var file_using_slash = file.split(path.sep).join('/')
```
Comment (clayne11) [inline index.js]: camelCase variable names please.

**Comment by exKAZUu** [comment]
Thank you for your comments. Done.

**Comment by clayne11** [comment]
Released as [`v0.3.3`](https://github.com/clayne11/eslint-import-resolver-meteor/releases/tag/v0.3.3)

**Comment by exKAZUu** [comment]
Thanks! I now confirmed that v0.3.3 worked well on Windows :+1:
